setwd("~/Documents/2021/Gaze-Cueing/")
## Dataset1b ##

#Load data

load(file = "Data/dataset1b/derived/q.mean.2.1.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.1_simple.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.1_t0.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.1_z.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.1_v.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.1_t0-z.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.1_t0-v.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.1_z-v.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.1_complex.Rdata")

load(file = "Data/dataset1b/derived/q.mean.2.2.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.2_simple.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.2_t0.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.2_z.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.2_v.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.2_t0-z.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.2_t0-v.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.2_z-v.Rdata")
load(file = "Data/dataset1b/derived/q.mean.2.2_complex.Rdata")

load(file = "Data/dataset1b/derived/p.mean.1.Rdata")
load(file = "Data/dataset1b/derived/p.mean.1_simple.Rdata")
load(file = "Data/dataset1b/derived/p.mean.1_t0.Rdata")
load(file = "Data/dataset1b/derived/p.mean.1_z.Rdata")
load(file = "Data/dataset1b/derived/p.mean.1_v.Rdata")
load(file = "Data/dataset1b/derived/p.mean.1_t0-z.Rdata")
load(file = "Data/dataset1b/derived/p.mean.1_t0-v.Rdata")
load(file = "Data/dataset1b/derived/p.mean.1_z-v.Rdata")
load(file = "Data/dataset1b/derived/p.mean.1_complex.Rdata")

load(file = "Data/dataset1b/derived/p.mean.2.Rdata")
load(file = "Data/dataset1b/derived/p.mean.2_simple.Rdata")
load(file = "Data/dataset1b/derived/p.mean.2_t0.Rdata")
load(file = "Data/dataset1b/derived/p.mean.2_z.Rdata")
load(file = "Data/dataset1b/derived/p.mean.2_v.Rdata")
load(file = "Data/dataset1b/derived/p.mean.2_t0-z.Rdata")
load(file = "Data/dataset1b/derived/p.mean.2_t0-v.Rdata")
load(file = "Data/dataset1b/derived/p.mean.2_z-v.Rdata")
load(file = "Data/dataset1b/derived/p.mean.2_complex.Rdata")

pdf(paste("Manuscript-figures/combined-fits-1b.pdf",sep=""),width=3*4,height=(3*4)+3)
#create matrix "m" which is the size of how many plots I'm going to have. 0 is where there's no plots,
m=matrix(1:9,nrow=3,byrow=T)
m=rbind(0,cbind(0,m,0),0)
m=cbind(m[,1:2],0,m[,3],0,m[,4:5])
m=rbind(m[1:2,],0,m[3,],0,m[4,], m[5,])
layout(mat=m,
       widths=c(0,1,0,1,0,1,0),
       heights=c(0,1,0,1,0,1,0))
#par(mar=rep(0,4))
par(mar=c(2.1,4.6,6,1))

plot(q.mean.2.1,qs*p.mean.1,pch=16, cex = 0.9, xlab = "", ylab = "", main = "Simple Model") 
points(q.mean.2.1_s,qs*p.mean.1_s,pch=17, cex = 0.9, type = "l")
points(q.mean.2.1_s,qs*p.mean.1_s,pch=17, cex = 0.9)
points(q.mean.2.2,qs*p.mean.2,pch=1, cex = 0.9) 
points(q.mean.2.2_s,qs*p.mean.2_s,pch=17, cex = 0.9)
points(q.mean.2.2_s,qs*p.mean.2_s,pch=2, type = "l", cex = 0.9)

plot(q.mean.2.1,qs*p.mean.1,pch=16, cex = 0.9, xlab = "", ylab = "", main = "t0 Model") 
points(q.mean.2.1_t0,qs*p.mean.1_t0,pch=17, cex = 0.9, type = "l")
points(q.mean.2.1_t0,qs*p.mean.1_t0,pch=17, cex = 0.9)
points(q.mean.2.2_t0,qs*p.mean.2_t0,pch=2, cex = 0.9)
points(q.mean.2.2_t0,qs*p.mean.2_t0,pch=2, type = "l", cex = 0.9)
points(q.mean.2.2,qs*p.mean.2,pch=1, cex = 0.9)

plot(q.mean.2.1,qs*p.mean.1,pch=16, cex = 0.9, xlab = "", ylab = "", main = "z Model") 
points(q.mean.2.1_z,qs*p.mean.1_z,pch=17, cex = 0.9, type = "l")
points(q.mean.2.1_z,qs*p.mean.1_z,pch=17, cex = 0.9)
points(q.mean.2.2_z,qs*p.mean.2_z,pch=2, cex = 0.9)
points(q.mean.2.2_z,qs*p.mean.2_z,pch=2, type = "l", cex = 0.9)
points(q.mean.2.2,qs*p.mean.2,pch=1, cex = 0.9)

plot(q.mean.2.1,qs*p.mean.1,pch=16, cex = 0.9, xlab = "", ylab = "", main = "v Model") 
points(q.mean.2.1_v,qs*p.mean.1_v,pch=17, cex = 0.9, type = "l")
points(q.mean.2.1_v,qs*p.mean.1_v,pch=17, cex = 0.9)
points(q.mean.2.2_v,qs*p.mean.2_v,pch=2, cex = 0.9)
points(q.mean.2.2_v,qs*p.mean.2_v,pch=2, type = "l", cex = 0.9)
points(q.mean.2.2,qs*p.mean.2,pch=1, cex = 0.9)

plot(q.mean.2.1,qs*p.mean.1,pch=16, cex = 0.9, xlab = "", ylab = "", main = "t0-z Model") 
points(q.mean.2.1_z_t0,qs*p.mean.1_z_t0,pch=17, cex = 0.9, type = "l")
points(q.mean.2.1_z_t0,qs*p.mean.1_z_t0,pch=17, cex = 0.9)
points(q.mean.2.2_z_t0,qs*p.mean.2_z_t0,pch=2, cex = 0.9)
points(q.mean.2.2_z_t0,qs*p.mean.2_z_t0,pch=2, type = "l", cex = 0.9)
points(q.mean.2.2,qs*p.mean.2,pch=1, cex = 0.9)

plot(q.mean.2.1,qs*p.mean.1,pch=16, cex = 0.9, xlab = "", ylab = "", main = "t0-v Model") 
points(q.mean.2.1_v_t0,qs*p.mean.1_v_t0,pch=17, cex = 0.9, type = "l")
points(q.mean.2.1_v_t0,qs*p.mean.1_v_t0,pch=17, cex = 0.9)
points(q.mean.2.2_v_t0,qs*p.mean.2_v_t0,pch=2, cex = 0.9)
points(q.mean.2.2_v_t0,qs*p.mean.2_v_t0,pch=2, type = "l", cex = 0.9)
points(q.mean.2.2,qs*p.mean.2,pch=1, cex = 0.9)

plot(q.mean.2.1,qs*p.mean.1,pch=16, cex = 0.9, xlab = "", ylab = "", main = "z-v Model") 
points(q.mean.2.1_v_z,qs*p.mean.1_v_z,pch=17, cex = 0.9, type = "l")
points(q.mean.2.1_v_z,qs*p.mean.1_v_z,pch=17, cex = 0.9)
points(q.mean.2.2_v_z,qs*p.mean.2_v_z,pch=2, cex = 0.9)
points(q.mean.2.2_v_z,qs*p.mean.2_v_z,pch=2, type = "l", cex = 0.9)
points(q.mean.2.2,qs*p.mean.2,pch=1, cex = 0.9)

plot(q.mean.2.1,qs*p.mean.1,pch=16, cex = 0.9, xlab = "", ylab = "", main = "Complex Model") 
points(q.mean.2.1Complex,qs*p.mean.1Complex,pch=17, cex = 0.9, type = "l")
points(q.mean.2.1Complex,qs*p.mean.1Complex,pch=17, cex = 0.9)
points(q.mean.2.2Complex,qs*p.mean.2Complex,pch=2, cex = 0.9)
points(q.mean.2.2Complex,qs*p.mean.2Complex,pch=2, type = "l", cex = 0.9)
points(q.mean.2.2,qs*p.mean.2,pch=1, cex = 0.9)

dev.off()
