#! /bin/bash
cd ~/Documents/2021/Gaze-Cueing/Modelling-Unconstrained/dataset1a
Rscript 05.1_runDiffModel_V-Z.R
Rscript 05.2_runDiffModel_Z.R
Rscript 05.3_runDiffModel_Z-t0.R
Rscript 05.4_runDiffModel_t0.R
Rscript 05.5_runDiffModel_V.R
Rscript 05.6_runDiffModel_V-t0.R
Rscript 05.7_runDiffModel_all-params.R
Rscript 05.8_runDiffModel_simple.R
Rscript 06_Weight-Plots.R
Rscript 09.1_quantiles_alt.R
Rscript 09.2_quantiles_null.R
Rscript 09.3_quantiles_all.R
